// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createChunk = `-- name: CreateChunk :one
INSERT INTO chunks(content, tags) VALUES (?,?) RETURNING id, content, tags
`

type CreateChunkParams struct {
	Content string
	Tags    interface{}
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error) {
	row := q.db.QueryRowContext(ctx, createChunk, arg.Content, arg.Tags)
	var i Chunk
	err := row.Scan(&i.ID, &i.Content, &i.Tags)
	return i, err
}

const getChunks = `-- name: GetChunks :many
SELECT id, content, tags FROM chunks LIMIT ? OFFSET ?
`

type GetChunksParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetChunks(ctx context.Context, arg GetChunksParams) ([]Chunk, error) {
	rows, err := q.db.QueryContext(ctx, getChunks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chunk
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(&i.ID, &i.Content, &i.Tags); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
